name: strapi-boilerplate

on: push
jobs:
    buld:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                node-version: '18.x'
                cache: 'npm'
            - uses: hexlet-components/hello-from-hexlet-action@release

            - run: echo "Workflow - $GITHUB_WORKFLOW"
            - run: ls -la
            - run: make setup
            - run: make test
            - run: make lint
